name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java (JDK)
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar y empaquetar en JAR
        run: |
          javac GitHubBackupApp.java
          jar cfe GitHubBackupApp.jar GitHubBackupApp GitHubBackupApp.class

      - name: Crear ejecutable con jpackage
        run: |
          jpackage --type app-image --name GitHubBackup --input . --main-jar GitHubBackupApp.jar --main-class GitHubBackupApp --win-console

      - name: Subir como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: GitHubBackup-Windows
          path: GitHubBackup/
